print("Hello world!")
print("Hello again!")
print("I like typing this")
print("This is fun")
# print("This is not fun for me")
print("Yay! Printing")
print("I'd much rather you 'not'")
print('I said "do not" touch this')